### ISSUE TITLE
Build and test FANS in a GitHub Action

### ISSUE THREAD

**Issue by IshaanDesai** [DataAnalyticsEngineering/FANS#9]
FANS needs to be built and testing in a GitHub Action, to catch potential changes which will disrupt the build process or introduce bugs, for example, like what was seen in https://github.com/DataAnalyticsEngineering/FANS/pull/7

A workflow file already exists: https://github.com/DataAnalyticsEngineering/FANS/blob/develop/.github/workflows/build_and_package.yaml but needs to be refined and made workable.

**Comment by siggmo** [comment]
I would be happy to work on this :)

The existing GitHub Action works already ([test run](https://github.com/DataAnalyticsEngineering/FANS/actions/runs/10575319831) with `workflow_dispatch`).

I thought of refining it, taking inspiration from [preCICE](https://github.com/precice/precice/blob/develop/.github/workflows/build-and-test.yml) once again :D (e.g. use `container` option of the Actions API instead of direct commands like `docker create` etc.).

We need it to run on pushes to `main` and `develop`, right? I guess it should also run on PRs?

I already have a draft setup of unit tests on my local machine which I would include here.

To keep things simple I would drop the generation of Debian packages as they are anyway not the intended way of shipping FANS. If I understand correctly this action should only report build and test errors and not be concerned with packaging and other stuff, right?

Please tell me if you have any hints and suggestions that I should take into consideration, thanks!

**Comment by IshaanDesai** [comment]
Let us build and test FANS for every push to main and develop, and also for every pull request.

> Please tell me if you have any hints and suggestions that I should take into consideration, thanks!

Nothing comes to mind right now.

**Comment by IshaanDesai** [comment]
Resolved via https://github.com/DataAnalyticsEngineering/FANS/pull/19
